//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Progress
    {
        public int Lab_Id { get; set; }
        public int S_Id { get; set; }
        public Nullable<bool> Submited { get; set; }
        public Nullable<bool> Accepted { get; set; }
        public Nullable<int> Mark { get; set; }
    
        public virtual Lab Lab { get; set; }
        public virtual Student Student { get; set; }
    }
}
