//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Speciality
    {
        public Speciality()
        {
            this.Groups = new HashSet<Group>();
        }
    
        public int Spec_Id { get; set; }
        public string Spec_Name { get; set; }
        public string Spec_Code { get; set; }
    
        public virtual ICollection<Group> Groups { get; set; }
    }
}
