//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public Student()
        {
            this.Labs = new HashSet<Lab>();
            this.Progresses = new HashSet<Progress>();
        }
    
        public int S_id { get; set; }
        public string S_Name { get; set; }
        public string S_Address { get; set; }
        public string S_Tel { get; set; }
        public string S_Mail { get; set; }
        public Nullable<int> Gr_Id { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual ICollection<Lab> Labs { get; set; }
        public virtual ICollection<Progress> Progresses { get; set; }
    }
}
