//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeacherModule.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public Subject()
        {
            this.Labs = new HashSet<Lab>();
            this.Lessons = new HashSet<Lesson>();
        }
    
        public int Subj_Id { get; set; }
        public string Subj_Name { get; set; }
    
        public virtual ICollection<Lab> Labs { get; set; }
        public virtual ICollection<Lesson> Lessons { get; set; }
    }
}
